# My Config

timeRange = 604800  # range of time to consider, 604800 is 1 week
maxCommits = 1000  # maximum commits to consider per project
# Adapted from https://github.com/cryptodotis/code-peer-review/blob/master/tags.txt
keywords = [
  # Block ciphers
  "AES ",

  # Block cipher modes
  "-ECB ",
  "-CBC ",
  "-CFB ",
  "-OFB ",
  "-CTR ",
  "-CCM ",
  "-GCM ",
  " ECB ",
  " CBC ",
  " CFB ",
  " OFB ",
  " CTR ",
  " CCM ",
  " GCM ",

  # Stream ciphers
  "ChaCha",
  "Salsa",

  # Hash functions
  " Blake ",
  " MD5 ",
  " SHA2 ",
  " SHA3 ",
  " SHA224 ",
  " SHA256 ",
  " SHA384 ",
  " SHA512 ",
  " SHA-224 ",
  " SHA-256 ",
  " SHA-384 ",
  " SHA-512 ",
  " RipeMD ",
  " Keccak ",

  # MAC
  " HMAC",
  "CBC-MAC",
  "Encrypt-then-MAC",
  "MAC-then-Encrypt",

  # Key derivation
  " KDF ",
  " PBKDF ",
  " bcrypt ",
  " scrypt ",
  " argon2 ",

  # Randomness
  " rng ",
  " prng ",
  " csprng ",

  # Public key
  " DSA ",
  " RSA ",
  " ECDH ",
  " ECDSA ",
  " ECC ",
  "curve25519",
  "ed25519",
  "x25519",
  "curve448",
  "ed448",
  "x448",
  " P256 ",
  " P-256 ",

  # Crypto projects
  "OpenSSL",
  " NSS ",
  "botan",
  "bouncycastle",

  # Transport security
  " TLS ",
  " SSL ",
  " TLS 1.1 ",
  " TLS 1.2 ",
  " TLS 1.3 ",
  " TLSv1.1 ",
  " TLSv1.2 ",
  " TLSv1.3 ",

  # Public key infra
  "X509",
  "X.509",

  # Authentication
  "OAuth",
]

[projects]

#
# Anonymity Projects
#

[projects.Tor]
url = "https://git.torproject.org/tor.git"
branch = "master"
commitUrlPrefix = "https://gitweb.torproject.org/tor.git/commit/?id="

#
# The Internet Bug Bounty (Selected)
#

# TODO: add specific python packages & ruby gems.

[projects.RubyGems]
url = "https://github.com/rubygems/rubygems.git"
branch = "master"
commitUrlPrefix = "https://github.com/rubygems/rubygems/commit/"

[projects.Phabricator]
url = "https://github.com/phacility/phabricator.git"
branch = "master"
commitUrlPrefix = "https://github.com/phacility/phabricator/commit/"

[projects.Rails]
url = "https://github.com/rails/rails.git"
branch = "master"
commitUrlPrefix = "https://github.com/rails/rails/commit/"

[projects.FFMPEG]
url = "https://git.videolan.org/git/ffmpeg.git"
branch = "master"
commitUrlPrefix = "https://git.videolan.org/?p=ffmpeg.git;a=commit;h="

[projects.Libav]
url = "https://github.com/libav/libav.git"
branch = "master"
commitUrlPrefix = "https://github.com/libav/libav/commit/"

# TODO: Maybe https://github.com/the-tcpdump-group/libpcap
# TODO: Maybe https://github.com/the-tcpdump-group/tcpdump
# TODO: Add hg support and add http://hg.code.sf.net/p/graphicsmagick/code/

[projects.ImageMagick]
url = "https://github.com/ImageMagick/ImageMagick.git"
branch = "master"
commitUrlPrefix = "https://github.com/ImageMagick/ImageMagick/commit/"

[projects.libpng]
url = "https://github.com/glennrp/libpng.git"
branch = "master"
commitUrlPrefix = "https://github.com/glennrp/libpng/commit/"

[projects.OpenSSL]
url = "https://github.com/openssl/openssl.git"
branch = "master"
commitUrlPrefix = "https://github.com/openssl/openssl/commit/"

#
# Selected crypto packages
#

[projects.BouncyCastle]
url = "https://github.com/bcgit/bc-java.git"
branch = "master"
commitUrlPrefix = "https://github.com/bcgit/bc-java/commit/"

[projects.NSS]
url = "https://github.com/nss-dev/nss.git"
branch = "master"
commitUrlPrefix = "https://github.com/nss-dev/nss/commit/"
